services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - gemini_network

  worker:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python gemini_worker.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - gemini_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
    networks:
      - gemini_network

networks:
  gemini_network:
    driver: bridge
